# Generated by Django 4.2 on 2023-04-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
                ('country_id', models.CharField(max_length=1, null=True)),
                ('manufacturer_id', models.CharField(max_length=6, null=True)),
                ('product_id', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
