# Generated by Django 4.2 on 2023-04-06 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('barcode', models.ImageField(blank=True, upload_to='images/')),
                ('country_code', models.CharField(max_length=3, null=True)),
                ('manufacturer_code', models.CharField(max_length=5, null=True)),
                ('product_code', models.CharField(max_length=5, null=True)),
            ],
        ),
    ]
